spring:
  application:
    name: "building_management"
  datasource:
    url: jdbc:h2:mem:testbdb
    username: tz
    password: ''
    driver-class-name: org.h2.Driver
  h2:
    console:
      enabled: true
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
server:
  port: 8080
